
flib_version=0.2.0
flib_file=8117455

mod_id=plaingrinder
curse_id=452000
curse_slug=plain-grinder
mod_version=1.4.2
mod_name=plaingrinder
mod_group_id=com.lothrazar.plaingrinder
mod_license=SeeGithub
mod_authors=Lothrazar
mod_description=mod

modrinth_id=
